dynamic_goal2:
  ros__parameters:
    origin_frame: "map"
    robot_frame: "base_footprint"
    rviz_line_visualization: false
    rviz_circle_visualization: true

    # Thresholds
    movement_threshold: 0.50
    rotational_threshold: 0.90

    full_circle: 0.8 # FIXME
    granularity: 0.1
    number_points: 50
    occupancy_path: 90.0
    radius: 0.50
    rate: 0.50